### PR TITLE
Re-add convenience Flutter gen command

### PR DESCRIPTION
**Pull request by dangeross**
Re-add the convenience Flutter `gen` command to generate code/FFI bindings and softlink C headers

### CODE REVIEW

**Review by roeierez — APPROVED** [review]

**Review by erdemyerebasmaz — COMMENTED** [review]
Where is this being used?

uniFFI headers are non-existent when`build-uniffi-swift` is not run and `ffigen` relies on both frb & uniFFI C headers.

**Comment by dangeross** [comment]
> Where is this being used?

@erdemyerebasmaz we need a single command people can run to generate everything needed for Flutter when developing the SDK. What do you suggest to add?

**Comment by erdemyerebasmaz** [comment]
> > Where is this being used?
> 
> @erdemyerebasmaz we need a single command people can run to generate everything needed for Flutter when developing the SDK. What do you suggest to add?

That command is `just bootstrap true true`

> > Where is this being used?
> 
> @erdemyerebasmaz we need a single command people can run to generate everything needed for Flutter when developing the SDK. What do you suggest to add?

I'd decouple uniFFI C header file generation from `just build-uniffi-swift` / `make bindings-swift` scripts if possible and make it part of `gen` / `bootstrap` recipes.

**Comment by erdemyerebasmaz** [comment]
> I'd decouple uniFFI C header file generation from `just build-uniffi-swift` / `make bindings-swift` scripts if possible and make it part of `gen` / `bootstrap` recipes.

Decoupled uniFFI C header file generation from `just build-uniffi-swift` / `make bindings-swift` scripts.

> > we need a single command people can run to generate everything needed for Flutter when developing the SDK.

Created a single command, `just build` recipe to build the uniFFI library & generate Dart/Flutter & FFI bindings.

`just gen` can be used without rebuilding the libraries if there are no structural changes to save development time. It also has an option to skip building iOS framework, `just gen false`.

**Pull request merged**
