### PR TITLE
`GetInfoResponse`: add fingerprint

### PR DESCRIPTION
**Pull request by ok300**
This PR adds the wallet's `fingerprint` to `GetInfoResponse`. This is useful because the fingerprint is used in building the working directory. It therefore helps callers better identify which working directory belongs to which wallet, in setups where several wallets (mnemonics) were used.

### CODE REVIEW

**Comment by dangeross** [comment]
This pubkey is currently used to register a webhook with the LNURL-pay service

**Comment by ok300** [comment]
@dangeross good catch.

If it's acting as an unique identifier of the wallet, would it make sense to use the fingerprint instead? Or is there a reason to use the pubkey in particular?

**Comment by dangeross** [comment]
> If it's acting as an unique identifier of the wallet, would it make sense to use the fingerprint instead? Or is there a reason to use the pubkey in particular

The LNURL service receives a signed request with a signature which is validated against the pubkey. The pubkey also needs to be "static" so the encoded LNURL doesn't change.

**Comment by dangeross** [comment]
Adding the fingerprint is good though, it solves an issue that @erdemyerebasmaz just found trying to export the database in Misty

**Comment by ok300** [comment]
Updated the PR to keep the pubkey and only add the fingerprint.

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM

**Review by dangeross — APPROVED** [review]
LGTM

**Pull request merged**
